name: Evaluate Student Agent

on:
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [run-evaluation]
  workflow_dispatch:

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Student Repository
        uses: actions/checkout@v3  

      - name: 2. Trigger Evaluation on Main Repository
        if: github.event_name == 'pull_request'
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -X POST -H "Authorization: Bearer $PAT" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/YOUR_USERNAME/RL-HW1-Template/dispatches \
               -d '{"event_type": "run-evaluation"}'


      - name: 3. Download eval.py from Private Repo
        if: github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
        run: |
          curl -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -o eval.py \
               "${{ secrets.EVAL_REPO }}"
          cat eval.py  # 顯示 eval.py 內容，確認是否下載成功

      - name: 4. Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: 5. Install Dependencies
        run: |
          pip install gym
          pip install -r requirements.txt

      - name: 6. Run Evaluation
        run: python eval.py --token ${{ secrets.SUBMIT_TOKEN }}
