name: Evaluate Student Agent

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Student Repository
        uses: actions/checkout@v3  

      - name: 2. Download eval.py from Private Repo
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -o eval.py \
               "${{ secrets.EVAL_REPO }}"

      - name: 3. Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: 4. Install Dependencies
        run: pip install -r requirements.txt

      - name: 5. Run Evaluation
        run: python eval.py --token ${{ secrets.SUBMIT_TOKEN }}
